services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: DfinanceUser
      POSTGRES_PASSWORD: DfinancePassword
      POSTGRES_DB: DfinanceDB
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dfinance-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U DfinanceUser -d DfinanceDB"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=DfinanceUser
      - DB_PASSWORD=DfinancePassword
      - DB_NAME=DfinanceDB
      - DB_PORT=5432
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - dfinance-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - dfinance-network
    restart: unless-stopped

volumes:
  db_data:

networks:
  dfinance-network:
    driver: bridge
