name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install
      
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install
      
    - name: Test Docker build
      run: docker-compose build
